# Generated by Django 4.1.7 on 2023-03-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
