# Generated by Django 4.1.7 on 2023-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_alter_email_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
