# Generated by Django 4.1.7 on 2023-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0004_alter_email_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
